# Generated by Django 4.1 on 2022-09-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato1', models.IntegerField(blank=True, null=True)),
                ('dato2', models.IntegerField(blank=True, null=True)),
                ('dato3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
