# Generated by Django 4.1 on 2022-09-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_dato1_post_dato2_post_dato3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dato1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dato2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dato3',
        ),
    ]
